### ISSUE TITLE
Modernize data representation

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-data-embed#119]
**Description**
If the response size of the dataset is too large, the response is invalid. better to truncate it.

**Comment by MarquiseRosier** [comment]
Guess querybuilder should help here too? @trieloff

**Comment by trieloff** [comment]
Not really. I wouldn’t apply a default truncation, as we don’t have a way of indicating that the result set has been truncated.

One possible solution would be to estimate how many elements would be ok and then send a redirect to the same URL with new QB limits applied. The client can then follow the redirect and accept the truncation.

**Comment by tripodsan** [comment]
maybe we should change the data format of the returned table, like maybe others do. just returning the plain JSON array is IMO not good.

minimal example:

**/bla.xls?limit=100&offset=50**
```json
{
  total: 5670,
  limit: 100,
  offset: 50,
  data: [ .... ]
}
```

example with force truncation

**/bla.xls?limit=3000*
```json
{
  total: 5670,
  limit: 2354,
  offset: 0,
  data: [ .... ]
}
```

this would also allow for a more efficient format for tables. eg:
**/bla.xls?limit=3000&type=matrix*
```json
{
  total: 5670,
  limit: 2354,
  offset: 0,
  type: 'matrix',
  columns: [ 'a', 'b', 'c', .... ]
  rows: [[0, 1, 2], [3, 4, 5], ...]
}
```

**Comment by tripodsan** [comment]
@davidnuescheler WDYT about adding the extra `data` property in the json response ?

**Comment by tripodsan** [comment]
or maybe similar than:

https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/collection-resources-and-pagination

```
{
  "skip": 0,
  "limit": 100,
  "total": 1256,
  "items": [ /* 100 individual resources */ ]
}
```
