### ISSUE TITLE
Return last modified date of a file in a header

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-data-embed#233]
In order to detect changes to a file, it would be helpful if data-embed would return the last modified date of that file, e.g. in the `Last-Modified` HTTP response header. 

This feature would particularly help in solving https://github.com/adobe/theblog/issues/550

**Comment by trieloff** [comment]
Sounds reasonable.

**Comment by tripodsan** [comment]
doesn't `getWorkbook()` return the last modified date?
https://github.com/adobe/helix-data-embed/blob/master/src/matchers/excel.js#L31

**Comment by dominique-pfister** [comment]
> doesn't `getWorkbook()` return the last modified date?
> https://github.com/adobe/helix-data-embed/blob/master/src/matchers/excel.js#L31

I don't think so: getWorkbook() just creates an instance of Workbook, adding a reference to `OneDrive` and the _coordinates_ of the workbook:
https://github.com/adobe/helix-onedrive-support/blob/master/src/Workbook.js#L21-L27
