### ISSUE TITLE
Filter values using URL parameters

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-data-embed#34]
If you have a long table of data, but want to restrict the response to a small subset (maybe just one row), it would be useful to have a number of URL parameters that can be used to filter the result set.

I'm seeing following options:

1. port the [AEM QueryBuilder](https://docs.adobe.com/content/help/en/experience-manager-65/developing/platform/query-builder/querybuilder-api.html) – the query builder was designed to express complex queries in the form of URL parameters that are easily assembled and would provide one additional layer of compatibility with AEM
2. use [ODATA Query Parameters](https://docs.microsoft.com/en-us/graph/query-parameters) – this would make the implementation for Excel trivial because we can just pass on the parameter
3. use [MongoDB Query Operators as URL parameters](https://restdb.io/docs/querying-with-the-api) – relatively easy to build with [sift](https://www.npmjs.com/package/sift)

@davidnuescheler @rofe @tripodsan which of the three options would you like to see?

`https://adobe.sharepoint.com/sites/TheBlog/_layouts/15/guestaccess.aspx?share=ESR1N29Z7HpCh1Zfs_0YS_gB4gVSuKyWRut-kNcHVSvkew&email=helix%40adobe.com&e=hx0OUl&property=url&property.value=https://theblog.adobe.com/silka-miesnieks-designing-immersive-world/&property.operation=equals`

`https://adobe.sharepoint.com/sites/TheBlog/_layouts/15/guestaccess.aspx?share=ESR1N29Z7HpCh1Zfs_0YS_gB4gVSuKyWRut-kNcHVSvkew&email=helix%40adobe.com&e=hx0OUl&$filter=url eq 'https://theblog.adobe.com/silka-miesnieks-designing-immersive-world/'`

`https://adobe.sharepoint.com/sites/TheBlog/_layouts/15/guestaccess.aspx?share=ESR1N29Z7HpCh1Zfs_0YS_gB4gVSuKyWRut-kNcHVSvkew&email=helix%40adobe.com&e=hx0OUl&query={"url": "https://theblog.adobe.com/silka-miesnieks-designing-immersive-world/"}`

**Comment by rofe** [comment]
I'm leaning towards keeping it simple and this sounds like 2... 

Fwiw, Google Spreadsheets seems to allow passing a query string via their [visualization API](https://developers.google.com/chart/interactive/docs/reference).

**Comment by trieloff** [comment]
The simplest implementation would be 3, then 1, then 2. The most practical and readable URLs would be 1, then 2, then 3.

**Comment by rofe** [comment]
Do the URLs need to be readable? I would do whatever feels most natural for the user embedding the data.

**Comment by trieloff** [comment]
They need to be readable as they need to be writeable. Writing JSON as a URL parameter is hard. Writing in another query language that requires string escaping is hard, too.

Query Builder was designed to be writeable by relatively simple HTML forms.

**Comment by trieloff** [comment]
I'm going to try and build the query builder approach.
