### ISSUE TITLE
Remove query-builder support?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-data-embed#364]
As we have been breaking compatibility with v3 anyway, should we remove query builder support while we are at it?

**Comment by tripodsan** [comment]
> As we have been breaking compatibility with v3 anyway, should we remove query builder support while we are at it?

but keep `limit` and `offset`, I think :-)

**Comment by trieloff** [comment]
`limit` and `offset` are not part of the query builder API, they are just something made up on the spot. The OB equivalents are `p.limit` and `p.offset`
