### ISSUE TITLE
Expose real file name

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-data-embed#423]
The data are requested via a json request which means the Excel / Sheet document is known via its url. When you need to expose a "friendly" name of the document, only option at the moment is to extract it from the URL. Main issue: the real file name can be different from the original document: `7174_Helix_WS_Pilot_Sep` would become `7174-Helix-WS-Pilot-Sep`. 

2 options: 
1. educate the author to use only dashes and be aware of the URL rules
2. expose the real file name in the json response as a `name` property

While 1 is important for what is exposed externally (protect url namespace), we are starting to use spreadsheets for work tracking (translation batches) where here the filename matches user project names and won't be exposed as real public urls. 
2 is simple and should not hurt.

For publicly exposed urls, the name property will anyway be equal to the url last segment (minus the extension).

@trieloff @tripodsan WDYT ?

**Comment by tripodsan** [comment]
I don't understand why this is important for data-embed. 
for previewed and published content, you can always use the admin to get the correct URLs, eg:
https://admin.hlx3.page/preview/tripodsan/helix-test/main/data-embed-unit-tests/Example_Data.json

( which I now see is wrong :-)

**Comment by kptdobe** [comment]
The filename could serve a metadata in the response (maybe data-embed is not the right place). 
But for my use case, I make the extra call to the admin API anyway, thus I can use the `source.sourceLocation` to expose the "real" file name.
